### ISSUE TITLE
Remove vendor folder from repo

### ISSUE THREAD

**Issue by normanlolx** [JedI-O/jedio-timelime#1]
Hey! Vendor folders normally shouldn't be included into the repo, since they can get quite heavy (size). Everybody pulling/forking your repo will simply get all dependencies by calling npm install, so there's no need to include it here. The repo itself should be kept as clean as possible. Viele Grüße

**Comment by JedI-O** [comment]
Thanks for your note! We removed the folder and added it to gitignore.
